### ISSUE TITLE
Issue or not.

### ISSUE THREAD

**Issue by karuppasamy** [sindresorhus/matcher#12]
Are you intentionally implemented a code to get a result as below?.

<img width="553" alt="matcher" src="https://user-images.githubusercontent.com/264525/36050428-6d0c3fbc-0dde-11e8-9a7c-ff7fad00899f.png">

From the documentation,

```
matcher(['foo', 'bar', 'moo'], ['*oo', '!foo']);
//=> ['moo']
```

[First example]: if you change the order of the pattern elements, `matcher` is returning all the elements from the input. (Question: Is there any order preference in the pattern elements like, non-match (!) pattern element should come always last?)

```
matcher(['foo', 'bar', 'moo'], ['!foo', '*oo']);
//=> ['foo', 'bar', 'moo']
```

In my second example, I used three elements in the pattern match array `['*oo', '!foo', '*o']`. The third match is overriding the first one and it doesn't care about the second match (!foo - non-match). Hence, `matcher` is returning both `foo` and `moo`. 

```
matcher(['foo', 'bar', 'moo'], ['*oo', '!foo', '*o']);
//=> ['foo', 'moo']
```

**Comment by SamVerschueren** [comment]
What do you mean exactly?

**Comment by karuppasamy** [comment]
I have updated the question which I thought to ask.  I would like to close this issue, since I got an understanding while writing the question in elaborate and from the code implementation too. 

-Writing is always good- Thanks.
