### ISSUE TITLE
.isMatch support collection

### ISSUE THREAD

**Issue by Kikobeats** [sindresorhus/matcher#15]
Hello, what do you think add collection support to `.isMatch`?

It will be equivalent using `matcher` or `.isMatch`, just making different the output

```js
matcher(['foo', 'bar', 'moo'], ['*oo', '!foo']); //=> ['moo']
```

Using `.isMatch`

```js
matcher.isMatch(['foo', 'bar', 'moo'], ['*oo', '!foo']) // => true 
```

**Comment by sindresorhus** [comment]
Sure, PR welcome ;)
