### ISSUE TITLE
ES5 support

### ISSUE THREAD

**Issue by draperunner** [sindresorhus/matcher#17]
Hi!

The template literals and arrow functions break our build for Internet Explorer 11. Could you please consider transpiling the library to ES5 – or simply use ES5 – in order to support more browser versions?

Takk :)

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.
