### ISSUE TITLE
Empty pattern array on `.isMatch` should not match

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/matcher#22]
I would expect this to return `false` because if there are no patterns, there can not be a match.

``` js
> require("matcher").isMatch("hi", []);
true
```

**Comment by silverwind** [comment]
I guess technically one can interpret a array of "all patterns" with no pattern present as a "matches everything".

**Comment by sindresorhus** [comment]
It could really be both. However, I'm slightly leaning towards this being a bug and that an empty array should mean that nothing should be matched. Not sure though. Regardless, the behavior needs to be clearly documented.

We also need to think about what patterns like `''` and `['']` should do.

**Comment by atjn** [comment]
Well, the current behaviour is:
```
''       //false
['']     //false
['', ''] //false
[]       //true
```
I would argue that they should either all be `true` or all be `false`, and the smallest breaking change would be to change the emtpy array to `false`.

I just encountered this problem in a project, and I would have to write a lot of ugly code to fix it, so I'll try to submit a PR here instead.

**Comment by sindresorhus** [comment]
@atjn Yes, let's go with the empty array meaning `false`. PR welcome. The behavior should also be clearly documented.
