### ISSUE TITLE
Option to match any pattern in .isMatch

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/matcher#23]
`.isMatch` currently matches when every (`Array.prototype.every`) pattern matches, but I have a case where I need to match any (`Array.prototype.some`) pattern. Would you accept adding a option for that?

**Comment by silverwind** [comment]
Found another solution.

**Comment by Dangoo** [comment]
@silverwind and that would be?

**Comment by silverwind** [comment]
I ended up reimplementing this module. It did not suit my needs, this was just one of many issues.
