### ISSUE TITLE
Does not match across newlines

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/matcher#24]
```js
> require('matcher').isMatch('test\nhaha', 'test*')
false
```

I think the wildcard should match newline characters as well.

**Comment by sindresorhus** [comment]
I'll fix, but do you think there should be an option to disable this so it doesn't search over newlines? Maybe `singleLine` option or something. Or `multiLine`?

**Comment by novemberborn** [comment]
I don't think whether the string is multi-line or not is relevant for the stated purpose of this library:

> Useful when you want to accept loose string input and regexes/globs are too convoluted.

Whether you want to treat this as a breaking change I don't know. If so, maybe make `multiLine` opt-in for now?

**Comment by sindresorhus** [comment]
Done: https://github.com/sindresorhus/matcher/releases/tag/v3.0.0
