### ISSUE TITLE
Feature request: the 'all' option

### ISSUE THREAD

**Issue by valango** [sindresorhus/matcher#25]
The matcher option `all` would work like this:
```
matcher(package.keywords, ['regex', 'missing']);
//=> ['regexp', 'regexpr']
matcher(package.keywords, ['regex', 'missing'], {all: true});
//=> []
matcher(package.keywords.concat(['missing']), ['regex', 'allting'], {all: true});
//=> ['regexp', 'regexpr', 'missing']
```
Or, perhaps 'every' would be better name for this option.

**Comment by sindresorhus** [comment]
Can you explain the behavior? It's not clear to me why `all` would make it match an item that doesn't match any of the patterns.

**Comment by valango** [comment]
@sindresorhus I'm sorry for being too vague. The proposed option requires that all provided patterns have been matched positively agains at least once:
   * if they do, the `matcher()` gives the same result as always;
   * if some of the patterns was not 'satisfied', then the result will be an empty array.
 
I forked, implemented and I'm ready to make the pull request if you like the idea.
