### ISSUE TITLE
Case sensitive option

### ISSUE THREAD

**Issue by revelt** [sindresorhus/matcher#9]
hi all,

I saw it was discussed previously, but please consider adding case-sensitive option. I'm working on a project where I need to filter out an array of file names and use wildcards. Case does matter...

Code-wise, it's just a toggle on the regex flag and this feature would not break the existing apps, just implement default on "case insensitive = on" mode and let people turn it off.

What do you think?

Thanks for creating and maintaining this by the way.

**Comment by sindresorhus** [comment]
Sure. PR welcome :)

**Comment by Ricardo-Silva91** [comment]
Hello, I made a pull request with a proposed solution for this issue (#10).
Feedback is welcome 😄

**Comment by revelt** [comment]
Thanks everybody!
